{{- if .Values.query.ingress.enabled -}}
{{- $servicePort := .Values.query.service.port -}}
{{- $basePath := .Values.query.basePath -}}
{{- $legacy := false -}}
{{- if semverCompare "<=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
  {{- $legacy := true -}}
{{- end -}}

{{- if $legacy }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "jaeger.query.name" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: query
  {{- if .Values.query.ingress.annotations }}
  annotations:
    {{- toYaml .Values.query.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.query.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $basePath }}
            backend:

              {{- if $legacy }}
              serviceName: {{ template "jaeger.query.name" $ }}
              servicePort: {{ $servicePort }}
              {{- else }}
              service:
                name: {{ template "jaeger.query.name" $ }}
                port:
                  number: {{ $servicePort }}
              {{- end }}
    {{- end -}}
    {{- if .Values.query.ingress.health.exposed }}
          - path: /health
            backend:
              {{- if $legacy }}
              serviceName: {{ template "jaeger.query.name" $ }}
              servicePort: 16687
              {{- else }}
              service:
                name: {{ template "jaeger.query.name" $ }}
                port:
                  number: 16687
              {{- end }}
    {{- end -}}
  {{- if .Values.query.ingress.tls }}
  tls:
    {{- toYaml .Values.query.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
